apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w3lo741dq-nodejs 
  janus-idp.io/tekton: w3lo741dq-nodejs
  backstage.io/kubernetes-id: w3lo741dq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w3lo741dq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml